### ISSUE TITLE
QT6 Support

### ISSUE THREAD

**Issue by valador** [GuidanceOfGrace/XEdit-PACT#15]
For beta MO2 PACT not work
![изображение](https://user-images.githubusercontent.com/3517485/229087088-fcf23486-0774-4acc-8c1e-5bbc6ec1624c.png)

**Comment by GuidanceOfGrace** [comment]
Are you using MO2 version 2.4 or 2.5?

**Comment by valador** [comment]
> 

2.5

**Comment by GuidanceOfGrace** [comment]
There's a bug in the 2.5 version that causes this message to pop up frequently, use MO2 2.4

**Comment by valador** [comment]
> There's a bug in the 2.5 version that causes this message to pop up frequently, use MO2 2.4

I have gog version skyrim and v2.5 best for me, i just clean sseedit. You need add single file clean and start through mo2 without any hooks.
