### ISSUE TITLE
[WinError 87] | UnboundLocalError

### ISSUE THREAD

**Issue by evildarkarchon** [GuidanceOfGrace/XEdit-PACT#6]
I was testing out vortex mode on the latest version using the generic xedit.exe and doing it on my Skyrim LO (not sure if that's relevant) and I got this error:

```
CURRENTLY RUNNING :
Traceback (most recent call last):
  File "C:\Users\evild\source\repos\XEdit-PACT\pact_interface.py", line 319, in run
    self.cleaning_done = clean_plugins()
  File "C:\Users\evild\source\repos\XEdit-PACT\PACT_Start.py", line 420, in clean_plugins
    run_xedit(info.XEDIT_EXC_LOG, plugin)
  File "C:\Users\evild\source\repos\XEdit-PACT\PACT_Start.py", line 305, in run_xedit
    bat_process = subprocess.Popen(bat_command)
  File "C:\Users\evild\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\evild\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect
```

**Comment by GuidanceOfGrace** [comment]
This might have something to do with:
Traceback (most recent call last):
  File "PACT_Interface.py", line 319, in run
  File "PACT_Start.py", line 394, in clean_plugins
  File "PACT_Start.py", line 275, in run_xedit
UnboundLocalError: local variable 'bat_command' referenced before assignment 

Which is what some SSE players have been reporting, though the only way I could think of why it would trigger this one is if none of the if statements get satisfied for creating the bat_command, so subprocess basically tries to run nothing. I have yet to figure out what is missing from which if check.

**Comment by GuidanceOfGrace** [comment]
Also, if you get this error after setting the xEdit path for the first time or after changing it from SSEEdit to xEdit while PACT is still running, this would indicate that the issue might be that somehow PACT is not updating the XEDIT path in time.

And what warnings are you getting in VSCode for so many type: ignore comments? Nothing wrong, just curious.

**Comment by evildarkarchon** [comment]
I have the type checker on, so anything that's assigned a type it's not expecting (even if said assignment is correct) it complains. The ignore statements are just to tell the type checker to back off, the regular linter is still doing its thing. 
When it comes to the interface file, PyQt and PySide both use native-code modules and the type-checker can't get the data it needs to do its work, so it just gives a bunch of "unknown member" warnings. Basically, the log gets clogged up with vscode saying, essentially, "I don't know what this does". I keep it on because it gives me legitimate stuff like pointing out unbound variables and pointing out some legitimate type assignment mistakes.

**Comment by evildarkarchon** [comment]
The UnboundLocal error is probably because bat_command is not specified anywhere outside those if-statements. So pretty sure that something is happening that is making it so that none of the if-statements are triggered. I agree that the race condition with configparser might be to blame, not 100% sure on a solution to that, though.

**Comment by evildarkarchon** [comment]
You win the code-speed contest :) didn't realize my branch was behind until I posted my PR, lol.

**Comment by evildarkarchon** [comment]
```
    # If universal xedit (xedit.exe) executable is set.
    if "loadorder" in str(info.LOAD_ORDER_PATH) and str(info.XEDIT_EXE).lower() in xedit_list_universal:
        with open(info.LOAD_ORDER_PATH, "r", encoding="utf-8", errors="ignore") as LO_Check:
            if "FalloutNV.esm" in LO_Check.read():
                XEDIT_LOG_TXT = str(info.XEDIT_PATH).replace('xEdit.exe', 'FNVEdit_log.txt')
                if MO2Mode:
                    bat_command = f'"{info.MO2_PATH}" run "{info.XEDIT_PATH}" -a "-fnv -QAC -autoexit -autoload \\"{plugin_escape}\\""'
                else:
                    bat_command = f'"{info.XEDIT_PATH}" -a -fnv -QAC -autoexit -autoload "{plugin_name}"'

            elif "Fallout4.esm" in LO_Check.read():
                XEDIT_LOG_TXT = str(info.XEDIT_PATH).replace('xEdit.exe', 'FO4Edit_log.txt')
                if MO2Mode:
                    bat_command = f'"{info.MO2_PATH}" run "{info.XEDIT_PATH}" -a "-fo4 -QAC -autoexit -autoload \\"{plugin_escape}\\""'
                else:
                    bat_command = f'"{info.XEDIT_PATH}" -a -fo4 -QAC -autoexit -autoload "{plugin_name}"'

            elif "Skyrim.esm" in LO_Check.read():
                XEDIT_LOG_TXT = str(info.XEDIT_PATH).replace('xEdit.exe', 'SSEEdit_log.txt')
                if MO2Mode:
                    bat_command = f'"{info.MO2_PATH}" run "{info.XEDIT_PATH}" -a "-sse -QAC -autoexit -autoload \\"{plugin_escape}\\""'
                else:
                    bat_command = f'"{info.XEDIT_PATH}" -a -sse -QAC -autoexit -autoload "{plugin_name}"'
```
Pretty sure our error is somewhere in this code block. It works just fine if I set it to SSEEdit.exe, but if I use the generic xedit.exe, it gives me the blank bat_command error.

**Comment by evildarkarchon** [comment]
New PR to hopefully put this bug to bed.

**Comment by evildarkarchon** [comment]
Did a full run with generic xedit.exe and the only issue I had was with empty plugin crashes, but that's an xedit thing, so not much we can do about that.

**Comment by GuidanceOfGrace** [comment]
It might not be that xedit crashes in that case, could be that QAC has a check at the beginning to see how many records the plugin has and skips it immediately if it has 0. I didn't notice any errors from the xedit exception log that would indicate a crash.

**Comment by evildarkarchon** [comment]
```
Traceback (most recent call last):
  File "PACT_Interface.py", line 319, in run
    self.cleaning_done = clean_plugins()
  File "PACT_Start.py", line 450, in clean_plugins
    LO_Plugin_List = []
  File "PACT_Start.py", line 358, in run_xedit
    pass
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 528, in run
subprocess.CalledProcessError: Command '['powershell', '-command', 'Get-Content C:/Users/evild/Programs/Xedit 4.0/xEditException.log']' returned non-zero exit status 1.
```
[xEditException.log](https://github.com/GuidanceOfGrace/XEdit-PACT/files/10977285/xEditException.log)
This is what I get when I try to "clean" an empty plugin. Since QAC uses a filter, I'm guessing that since there is nothing to filter, it chokes. In the end, it's an xedit issue as far as I can tell.
Edit: Looking at it more closely, powershell is also crashing, I don't know exactly why, but I'm guessing that's what is causing the loop to break.

**Comment by GuidanceOfGrace** [comment]
Ah, now I get it. Looks like the empty plugin I was testing this on wasn't actually empty, or it didn't trigger the error for some reason. At least the error catching for this will be easy to implement. Thanks.

As for the powershell crash, I'm guessing xedit crashes so fast that it can't generate xEditException.log in time or leaves it in an awkward state. I'll be adding in the appropriate code shortly.

**Comment by evildarkarchon** [comment]
That makes sense

**Comment by evildarkarchon** [comment]
Added a couple more exceptions to catch in PR #11 
Had them pop up when I was doing my test run, but I'm not exactly sure what caused them, my only guess is it was still trying to call proc.kill() but by that point, proc is dead already. That is a complete guess, but it is a psutil error and that's the only bit of psutil code in that code block.

**Comment by evildarkarchon** [comment]
We seem to have fixed the issue and then some, gonna close the issue unless you think of something else.
